language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
sudo: false
deploy:
  provider: npm
  email: juerg.hunziker@gmail.com
  api_key:
    secure: pgP9vBCs0LcgJdM/D+GNZkCqQmJH1xh49QmU/lNxw1aPlHhRZ/mwI/GcBpG3IiHeTH/FFxYZjllSMwi1YpXP8LH9G2oizN0a+T13uYwEcPajbAlz/dtQK4vSEuafaifQCJ4fyAezMSg3mJ1yM1uWCZPvdpSP62kNw/cvkHvx6Ls=
  on:
    tags: true
    all_branches: true